// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResultCode int32

const (
	ResultCode_SUCCESS            ResultCode = 0
	ResultCode_ERROR              ResultCode = 1
	ResultCode_SIGN_VALIDATE_FAIL ResultCode = 401
	ResultCode_SIGN_TIMEOUT       ResultCode = 402
	ResultCode_ENTRY_NOT_FOUND    ResultCode = 403
)

var ResultCode_name = map[int32]string{
	0:   "SUCCESS",
	1:   "ERROR",
	401: "SIGN_VALIDATE_FAIL",
	402: "SIGN_TIMEOUT",
	403: "ENTRY_NOT_FOUND",
}

var ResultCode_value = map[string]int32{
	"SUCCESS":            0,
	"ERROR":              1,
	"SIGN_VALIDATE_FAIL": 401,
	"SIGN_TIMEOUT":       402,
	"ENTRY_NOT_FOUND":    403,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}

func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

type EntryType int32

const (
	EntryType_INVALIDATE EntryType = 0
	EntryType_HTTP       EntryType = 1
	EntryType_RPC        EntryType = 2
)

var EntryType_name = map[int32]string{
	0: "INVALIDATE",
	1: "HTTP",
	2: "RPC",
}

var EntryType_value = map[string]int32{
	"INVALIDATE": 0,
	"HTTP":       1,
	"RPC":        2,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}

func (EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

type EntryInfo struct {
	URI                  string    `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
	EntryType            EntryType `protobuf:"varint,2,opt,name=EntryType,proto3,enum=agent.EntryType" json:"EntryType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EntryInfo) Reset()         { *m = EntryInfo{} }
func (m *EntryInfo) String() string { return proto.CompactTextString(m) }
func (*EntryInfo) ProtoMessage()    {}
func (*EntryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}
func (m *EntryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryInfo.Unmarshal(m, b)
}
func (m *EntryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryInfo.Marshal(b, m, deterministic)
}
func (m *EntryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryInfo.Merge(m, src)
}
func (m *EntryInfo) XXX_Size() int {
	return xxx_messageInfo_EntryInfo.Size(m)
}
func (m *EntryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EntryInfo proto.InternalMessageInfo

func (m *EntryInfo) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *EntryInfo) GetEntryType() EntryType {
	if m != nil {
		return m.EntryType
	}
	return EntryType_INVALIDATE
}

type AgentRegisterReq struct {
	InstanceID           string       `protobuf:"bytes,1,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"`
	AryEntry             []*EntryInfo `protobuf:"bytes,2,rep,name=AryEntry,proto3" json:"AryEntry,omitempty"`
	Sign                 string       `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	TimeStamp            int64        `protobuf:"varint,4,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentRegisterReq) Reset()         { *m = AgentRegisterReq{} }
func (m *AgentRegisterReq) String() string { return proto.CompactTextString(m) }
func (*AgentRegisterReq) ProtoMessage()    {}
func (*AgentRegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}
func (m *AgentRegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRegisterReq.Unmarshal(m, b)
}
func (m *AgentRegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRegisterReq.Marshal(b, m, deterministic)
}
func (m *AgentRegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRegisterReq.Merge(m, src)
}
func (m *AgentRegisterReq) XXX_Size() int {
	return xxx_messageInfo_AgentRegisterReq.Size(m)
}
func (m *AgentRegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRegisterReq proto.InternalMessageInfo

func (m *AgentRegisterReq) GetInstanceID() string {
	if m != nil {
		return m.InstanceID
	}
	return ""
}

func (m *AgentRegisterReq) GetAryEntry() []*EntryInfo {
	if m != nil {
		return m.AryEntry
	}
	return nil
}

func (m *AgentRegisterReq) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *AgentRegisterReq) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type AgentRegisterRsp struct {
	Result               ResultCode `protobuf:"varint,1,opt,name=Result,proto3,enum=agent.ResultCode" json:"Result,omitempty"`
	Sign                 string     `protobuf:"bytes,2,opt,name=Sign,proto3" json:"Sign,omitempty"`
	TimeStamp            int64      `protobuf:"varint,3,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AgentRegisterRsp) Reset()         { *m = AgentRegisterRsp{} }
func (m *AgentRegisterRsp) String() string { return proto.CompactTextString(m) }
func (*AgentRegisterRsp) ProtoMessage()    {}
func (*AgentRegisterRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}
func (m *AgentRegisterRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRegisterRsp.Unmarshal(m, b)
}
func (m *AgentRegisterRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRegisterRsp.Marshal(b, m, deterministic)
}
func (m *AgentRegisterRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRegisterRsp.Merge(m, src)
}
func (m *AgentRegisterRsp) XXX_Size() int {
	return xxx_messageInfo_AgentRegisterRsp.Size(m)
}
func (m *AgentRegisterRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRegisterRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRegisterRsp proto.InternalMessageInfo

func (m *AgentRegisterRsp) GetResult() ResultCode {
	if m != nil {
		return m.Result
	}
	return ResultCode_SUCCESS
}

func (m *AgentRegisterRsp) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *AgentRegisterRsp) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type AgentUnRegisterReq struct {
	InstanceID           string       `protobuf:"bytes,1,opt,name=InstanceID,proto3" json:"InstanceID,omitempty"`
	AryEntry             []*EntryInfo `protobuf:"bytes,2,rep,name=AryEntry,proto3" json:"AryEntry,omitempty"`
	Sign                 string       `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
	TimeStamp            int64        `protobuf:"varint,4,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentUnRegisterReq) Reset()         { *m = AgentUnRegisterReq{} }
func (m *AgentUnRegisterReq) String() string { return proto.CompactTextString(m) }
func (*AgentUnRegisterReq) ProtoMessage()    {}
func (*AgentUnRegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}
func (m *AgentUnRegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentUnRegisterReq.Unmarshal(m, b)
}
func (m *AgentUnRegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentUnRegisterReq.Marshal(b, m, deterministic)
}
func (m *AgentUnRegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentUnRegisterReq.Merge(m, src)
}
func (m *AgentUnRegisterReq) XXX_Size() int {
	return xxx_messageInfo_AgentUnRegisterReq.Size(m)
}
func (m *AgentUnRegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentUnRegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgentUnRegisterReq proto.InternalMessageInfo

func (m *AgentUnRegisterReq) GetInstanceID() string {
	if m != nil {
		return m.InstanceID
	}
	return ""
}

func (m *AgentUnRegisterReq) GetAryEntry() []*EntryInfo {
	if m != nil {
		return m.AryEntry
	}
	return nil
}

func (m *AgentUnRegisterReq) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *AgentUnRegisterReq) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type AgentInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInfo) Reset()         { *m = AgentInfo{} }
func (m *AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()    {}
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}
func (m *AgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInfo.Unmarshal(m, b)
}
func (m *AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInfo.Marshal(b, m, deterministic)
}
func (m *AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInfo.Merge(m, src)
}
func (m *AgentInfo) XXX_Size() int {
	return xxx_messageInfo_AgentInfo.Size(m)
}
func (m *AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInfo proto.InternalMessageInfo

func (m *AgentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentInfo) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *AgentInfo) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type AgentKeepAliveNotify struct {
	AryEntry             []*EntryInfo `protobuf:"bytes,1,rep,name=AryEntry,proto3" json:"AryEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentKeepAliveNotify) Reset()         { *m = AgentKeepAliveNotify{} }
func (m *AgentKeepAliveNotify) String() string { return proto.CompactTextString(m) }
func (*AgentKeepAliveNotify) ProtoMessage()    {}
func (*AgentKeepAliveNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}
func (m *AgentKeepAliveNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentKeepAliveNotify.Unmarshal(m, b)
}
func (m *AgentKeepAliveNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentKeepAliveNotify.Marshal(b, m, deterministic)
}
func (m *AgentKeepAliveNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentKeepAliveNotify.Merge(m, src)
}
func (m *AgentKeepAliveNotify) XXX_Size() int {
	return xxx_messageInfo_AgentKeepAliveNotify.Size(m)
}
func (m *AgentKeepAliveNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentKeepAliveNotify.DiscardUnknown(m)
}

var xxx_messageInfo_AgentKeepAliveNotify proto.InternalMessageInfo

func (m *AgentKeepAliveNotify) GetAryEntry() []*EntryInfo {
	if m != nil {
		return m.AryEntry
	}
	return nil
}

type AgentKeepAliveRsp struct {
	AryAgent             []*AgentInfo `protobuf:"bytes,1,rep,name=AryAgent,proto3" json:"AryAgent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentKeepAliveRsp) Reset()         { *m = AgentKeepAliveRsp{} }
func (m *AgentKeepAliveRsp) String() string { return proto.CompactTextString(m) }
func (*AgentKeepAliveRsp) ProtoMessage()    {}
func (*AgentKeepAliveRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}
func (m *AgentKeepAliveRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentKeepAliveRsp.Unmarshal(m, b)
}
func (m *AgentKeepAliveRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentKeepAliveRsp.Marshal(b, m, deterministic)
}
func (m *AgentKeepAliveRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentKeepAliveRsp.Merge(m, src)
}
func (m *AgentKeepAliveRsp) XXX_Size() int {
	return xxx_messageInfo_AgentKeepAliveRsp.Size(m)
}
func (m *AgentKeepAliveRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentKeepAliveRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AgentKeepAliveRsp proto.InternalMessageInfo

func (m *AgentKeepAliveRsp) GetAryAgent() []*AgentInfo {
	if m != nil {
		return m.AryAgent
	}
	return nil
}

type AgentEntryCheckReq struct {
	URI                  string    `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
	EntryType            EntryType `protobuf:"varint,2,opt,name=EntryType,proto3,enum=agent.EntryType" json:"EntryType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AgentEntryCheckReq) Reset()         { *m = AgentEntryCheckReq{} }
func (m *AgentEntryCheckReq) String() string { return proto.CompactTextString(m) }
func (*AgentEntryCheckReq) ProtoMessage()    {}
func (*AgentEntryCheckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}
func (m *AgentEntryCheckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentEntryCheckReq.Unmarshal(m, b)
}
func (m *AgentEntryCheckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentEntryCheckReq.Marshal(b, m, deterministic)
}
func (m *AgentEntryCheckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentEntryCheckReq.Merge(m, src)
}
func (m *AgentEntryCheckReq) XXX_Size() int {
	return xxx_messageInfo_AgentEntryCheckReq.Size(m)
}
func (m *AgentEntryCheckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentEntryCheckReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgentEntryCheckReq proto.InternalMessageInfo

func (m *AgentEntryCheckReq) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *AgentEntryCheckReq) GetEntryType() EntryType {
	if m != nil {
		return m.EntryType
	}
	return EntryType_INVALIDATE
}

type AgentEntryCheckRsp struct {
	Result               ResultCode `protobuf:"varint,1,opt,name=Result,proto3,enum=agent.ResultCode" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AgentEntryCheckRsp) Reset()         { *m = AgentEntryCheckRsp{} }
func (m *AgentEntryCheckRsp) String() string { return proto.CompactTextString(m) }
func (*AgentEntryCheckRsp) ProtoMessage()    {}
func (*AgentEntryCheckRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}
func (m *AgentEntryCheckRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentEntryCheckRsp.Unmarshal(m, b)
}
func (m *AgentEntryCheckRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentEntryCheckRsp.Marshal(b, m, deterministic)
}
func (m *AgentEntryCheckRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentEntryCheckRsp.Merge(m, src)
}
func (m *AgentEntryCheckRsp) XXX_Size() int {
	return xxx_messageInfo_AgentEntryCheckRsp.Size(m)
}
func (m *AgentEntryCheckRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentEntryCheckRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AgentEntryCheckRsp proto.InternalMessageInfo

func (m *AgentEntryCheckRsp) GetResult() ResultCode {
	if m != nil {
		return m.Result
	}
	return ResultCode_SUCCESS
}

func init() {
	proto.RegisterType((*EntryInfo)(nil), "agent.EntryInfo")
	proto.RegisterType((*AgentRegisterReq)(nil), "agent.AgentRegisterReq")
	proto.RegisterType((*AgentRegisterRsp)(nil), "agent.AgentRegisterRsp")
	proto.RegisterType((*AgentUnRegisterReq)(nil), "agent.AgentUnRegisterReq")
	proto.RegisterType((*AgentInfo)(nil), "agent.AgentInfo")
	proto.RegisterType((*AgentKeepAliveNotify)(nil), "agent.AgentKeepAliveNotify")
	proto.RegisterType((*AgentKeepAliveRsp)(nil), "agent.AgentKeepAliveRsp")
	proto.RegisterType((*AgentEntryCheckReq)(nil), "agent.AgentEntryCheckReq")
	proto.RegisterType((*AgentEntryCheckRsp)(nil), "agent.AgentEntryCheckRsp")
	proto.RegisterEnum("agent.ResultCode", ResultCode_name, ResultCode_value)
	proto.RegisterEnum("agent.EntryType", EntryType_name, EntryType_value)
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0xda, 0x49, 0x1b, 0x4f, 0x20, 0x6c, 0x46, 0x95, 0x6a, 0x22, 0x84, 0x22, 0x9f, 0x42,
	0x85, 0x72, 0x08, 0x77, 0x90, 0xe5, 0xb8, 0xb0, 0xa2, 0x75, 0xac, 0xb5, 0x5d, 0x89, 0x53, 0x14,
	0xca, 0x26, 0x58, 0x34, 0xb6, 0xb1, 0x0d, 0x52, 0x3e, 0x83, 0xc2, 0x87, 0xf1, 0x49, 0xc8, 0x1b,
	0xd7, 0x71, 0x02, 0x11, 0x42, 0x5c, 0x7a, 0x1b, 0xcf, 0x7b, 0x7a, 0xef, 0xed, 0xcc, 0xc8, 0xd0,
	0x99, 0x2f, 0x45, 0x94, 0x8f, 0x92, 0x34, 0xce, 0x63, 0x6c, 0xc9, 0x0f, 0xe3, 0x12, 0x34, 0x3b,
	0xca, 0xd3, 0x35, 0x8b, 0x16, 0x31, 0x52, 0x50, 0x03, 0xce, 0x74, 0x32, 0x20, 0x43, 0x8d, 0x17,
	0x25, 0x8e, 0x4a, 0xd8, 0x5f, 0x27, 0x42, 0x57, 0x06, 0x64, 0xd8, 0x1d, 0xd3, 0xd1, 0x46, 0xa6,
	0xea, 0xf3, 0x2d, 0xc5, 0xb8, 0x25, 0x40, 0xcd, 0x02, 0xe6, 0x62, 0x19, 0x66, 0xb9, 0x48, 0xb9,
	0xf8, 0x8c, 0x4f, 0x01, 0x58, 0x94, 0xe5, 0xf3, 0xe8, 0x5a, 0xb0, 0x49, 0xa9, 0x5e, 0xeb, 0xe0,
	0x73, 0x68, 0x9b, 0xe9, 0x5a, 0x8a, 0xe8, 0xca, 0x40, 0x1d, 0x76, 0x76, 0x3d, 0x8a, 0x68, 0xbc,
	0x62, 0x20, 0x42, 0xd3, 0x0b, 0x97, 0x91, 0xae, 0x4a, 0x1d, 0x59, 0xe3, 0x13, 0xd0, 0xfc, 0x70,
	0x25, 0xbc, 0x7c, 0xbe, 0x4a, 0xf4, 0xe6, 0x80, 0x0c, 0x55, 0xbe, 0x6d, 0x18, 0xf1, 0x7e, 0xa6,
	0x2c, 0xc1, 0x67, 0x70, 0xc4, 0x45, 0xf6, 0xe5, 0x26, 0x97, 0x79, 0xba, 0xe3, 0x5e, 0xe9, 0xb8,
	0x69, 0x5a, 0xf1, 0x07, 0xc1, 0x4b, 0x42, 0x65, 0xa8, 0x1c, 0x32, 0x54, 0xf7, 0x0d, 0x7f, 0x10,
	0x40, 0xe9, 0x18, 0x44, 0xf7, 0x69, 0x0e, 0x16, 0x68, 0x32, 0x95, 0xdc, 0x35, 0x42, 0xd3, 0x99,
	0xaf, 0x44, 0x19, 0x43, 0xd6, 0xd8, 0x05, 0x85, 0xb9, 0xe5, 0x3b, 0x15, 0xe6, 0x16, 0x1c, 0x37,
	0x4e, 0x73, 0x69, 0xf1, 0x90, 0xcb, 0xda, 0x98, 0xc0, 0x89, 0x14, 0x79, 0x2b, 0x44, 0x62, 0xde,
	0x84, 0x5f, 0x85, 0x13, 0xe7, 0xe1, 0x62, 0xbd, 0x13, 0x9e, 0xfc, 0x2d, 0xbc, 0x61, 0x42, 0x6f,
	0x57, 0xa5, 0xd8, 0xc9, 0x46, 0x42, 0xf6, 0xf7, 0x24, 0xaa, 0xd8, 0xbc, 0x62, 0x18, 0x57, 0xe5,
	0x8c, 0xa5, 0xa0, 0xf5, 0x51, 0x5c, 0x7f, 0x2a, 0x66, 0xfc, 0xff, 0x27, 0xfc, 0xea, 0x77, 0xdd,
	0x7f, 0xba, 0x97, 0xb3, 0x05, 0xc0, 0xb6, 0x8b, 0x1d, 0x38, 0xf6, 0x02, 0xcb, 0xb2, 0x3d, 0x8f,
	0x36, 0x50, 0x83, 0x96, 0xcd, 0xf9, 0x94, 0x53, 0x82, 0xa7, 0x80, 0x1e, 0x7b, 0xed, 0xcc, 0xae,
	0xcc, 0x0b, 0x36, 0x31, 0x7d, 0x7b, 0x76, 0x6e, 0xb2, 0x0b, 0xfa, 0x4d, 0xc5, 0x1e, 0x3c, 0x90,
	0x80, 0xcf, 0x2e, 0xed, 0x69, 0xe0, 0xd3, 0x5b, 0x15, 0x4f, 0xe0, 0x91, 0xed, 0xf8, 0xfc, 0xdd,
	0xcc, 0x99, 0xfa, 0xb3, 0xf3, 0x69, 0xe0, 0x4c, 0xe8, 0x77, 0xf5, 0xac, 0xfe, 0x30, 0xec, 0x02,
	0x30, 0xe7, 0x4e, 0x8b, 0x36, 0xb0, 0x0d, 0xcd, 0x37, 0xbe, 0xef, 0x52, 0x82, 0xc7, 0xa0, 0x72,
	0xd7, 0xa2, 0xca, 0xf8, 0x27, 0x81, 0x96, 0x7c, 0x19, 0xbe, 0x84, 0xf6, 0xdd, 0x5d, 0xe2, 0x69,
	0x7d, 0xc4, 0xb5, 0x6b, 0xed, 0xff, 0x19, 0xc8, 0x12, 0xa3, 0x81, 0x26, 0x68, 0xd5, 0xe2, 0x50,
	0xaf, 0xf3, 0xea, 0xfb, 0xec, 0x1f, 0x44, 0x8c, 0x06, 0x4e, 0x00, 0xb6, 0x03, 0xc6, 0xc7, 0x75,
	0xe6, 0xce, 0x42, 0xfb, 0x87, 0xa0, 0x42, 0xe5, 0xfd, 0x91, 0xfc, 0x97, 0xbd, 0xf8, 0x15, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0xd2, 0x75, 0x14, 0xda, 0x04, 0x00, 0x00,
}
